### PR TITLE
[megaclisas-status]  fix for Hot spare drives from Dirk Melchers + JBOD + unconf'ed drives.

### PR DESCRIPTION
**Pull request by ElCoyote27**
[megaclisas-status]  Fix for nested arrays from dnleek and fix miscalculation of unconfigured drives...

### CODE REVIEW

**Comment by ElCoyote27** [comment]
This PR also includes #30
It fixes issues #29 and #31.

**Comment by ElCoyote27** [comment]
This PR now also includes #33

**Comment by eLvErDe** [comment]
Sorry been busy on mesos all day, ill try to handle this tonight

On February 11, 2016 3:22:53 PM GMT+01:00, "Vincent S. Cojot" <notifications@github.com> wrote:
>This PR now also includes #33 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/pull/34#issuecomment-182884590

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ElCoyote27** [comment]
Hi Adam,
Any chance you could take a look at this PR?
I've done better QA on it and it include other fixes contributed by users in other PR's (it's ugly, I know, but I needed their fixes as well).
Please let me know if that's acceptable.
Regards,
Vincent

**Comment by eLvErDe** [comment]
Sure I will, but I cannot fond time today, lets say I ll tomorrow... Worst case, next monday....

Le 12 février 2016 17:29:25 GMT+01:00, "Vincent S. Cojot" <notifications@github.com> a écrit :
>Hi Adam,
>Any chance you could take a look at this PR?
>I've done better QA on it and it include other fixes contributed by
>users in other PR's (it's ugly, I know, but I needed their fixes as
>well).
>Please let me know if that's acceptable.
>Regards,
>Vincent
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/pull/34#issuecomment-183398512

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Pull request merged**
