### PR TITLE
Merge PR #105 and #106

### PR DESCRIPTION
**Pull request by ElCoyote27**
Hi,
This integrates both https://github.com/eLvErDe/hwraid/pull/105 and 
https://github.com/eLvErDe/hwraid/pull/106
Please merge.. Thank you.

### CODE REVIEW

**Comment by eLvErDe** [comment]
Ok, I'll try ton find some time and look at this

**Comment by ElCoyote27** [comment]
@eLvErDe Hi, I added some minor fixes, please pull (for megaclisas-status)

**Comment by ElCoyote27** [comment]
I removed all tabs and replaced them with spaces, this is why github complains.
This version works for both python2 and python3:
```
$ sudo python3 megaclisas-status
-- Controller information --
-- ID | H/W Model          | RAM    | Temp | BBU    | Firmware     
c0    | PERC H730P Adapter | 2048MB | 58C  | Good   | FW: 25.5.6.0009 

-- Array information --
-- ID | Type   |    Size |  Strpsz |   Flags | DskCache |   Status |  OS Path | CacheCade |InProgress   
c0u0  | RAID-0 |   1818G |  512 KB | ADRA,WB |  Enabled |  Optimal | /dev/sda | None      |None         
c0u2  | RAID-0 |   1818G |  512 KB | ADRA,WB |  Enabled |  Optimal | /dev/sdb | None      |None         

-- Disk information --
-- ID   | Type | Drive Model                                      | Size     | Status          | Speed    | Temp | Slot ID  | LSI ID  
c0u0p0  | SSD  | S3YUNB0KC09340D Samsung SSD 860 EVO 2TB RVT03B6Q | 1.818 TB | Online, Spun Up | 6.0Gb/s  | 22C  | [32:0]   | 0       
c0u2p0  | SSD  | S3YUNB0KC09173D Samsung SSD 860 EVO 2TB RVT03B6Q | 1.818 TB | Online, Spun Up | 6.0Gb/s  | 21C  | [32:1]   | 1       
```

```
$ sudo python3 megaclisas-status
-- Controller information --
-- ID | H/W Model          | RAM    | Temp | BBU    | Firmware     
c0    | PERC H730P Adapter | 2048MB | 58C  | Good   | FW: 25.5.6.0009 

-- Array information --
-- ID | Type   |    Size |  Strpsz |   Flags | DskCache |   Status |  OS Path | CacheCade |InProgress   
c0u0  | RAID-0 |   1818G |  512 KB | ADRA,WB |  Enabled |  Optimal | /dev/sda | None      |None         
c0u2  | RAID-0 |   1818G |  512 KB | ADRA,WB |  Enabled |  Optimal | /dev/sdb | None      |None         

-- Disk information --
-- ID   | Type | Drive Model                                      | Size     | Status          | Speed    | Temp | Slot ID  | LSI ID  
c0u0p0  | SSD  | S3YUNB0KC09340D Samsung SSD 860 EVO 2TB RVT03B6Q | 1.818 TB | Online, Spun Up | 6.0Gb/s  | 22C  | [32:0]   | 0       
c0u2p0  | SSD  | S3YUNB0KC09173D Samsung SSD 860 EVO 2TB RVT03B6Q | 1.818 TB | Online, Spun Up | 6.0Gb/s  | 21C  | [32:1]   | 1       
```

**Comment by eLvErDe** [comment]
Hello,

Sorry for the way too long delay.
I started thinking about this again and will try to work on this tonight and this weekend.

Regards, Adam.

**Comment by eLvErDe** [comment]
Hello,

It has been merged but redone because I wanted to also include black formatting

**Pull request closed without merging**
