### PR TITLE
Handle python3 for mega{cli,raid}sas-status

### PR DESCRIPTION
**Pull request by AnatomicJC**
Hi @eLvErDe 

Just setup python3 as default python on Debian Stretch, and got some errors on megaraid wrapper scripts. I just added some missing brackets, and replace some deprecated stuff.

### CODE REVIEW

**Comment by nega0** [comment]
Check your whitespace. There is some "broken" whitespace in `megaclisas-status` (if I remember correctly), but you may have added more. ;)

**Comment by eLvErDe** [comment]
Definitely, but I'd like to review it. I'd like to take this as a chance to finally make this code a bit better :D

**Comment by ElCoyote27** [comment]
Please merge if you can.. This code works on RHEL7 (python2) and Fedora.

**Comment by eLvErDe** [comment]
I'll but I'll also add Black formatting and will try to fix most obvious pylints...

**Comment by ElCoyote27** [comment]
Ok, many thanks for that @eLvErDe

**Comment by C0rn3j** [comment]
Hi, I see this was approved a year ago, is it going to get merged?

**Comment by rlucassen2** [comment]
Please change dependencies in the debian package. I think a "bullseye" dist directory will be necessary. Today (september 15, 2020) the package megaclisas-status depends on "python" which will is removed in Debian Bullseye. AFAICS there are two solutions:

1) alter dependency to package "python2" and change "#!/usr/bin/python" to "#!/usr/bin/python2"

2) change the script to use python3 (I tried, but I'm not a developper) and change the dependency to package "python3"

As of today, there is no package called "python" anymore, only python2 or python3. The package "megaclisas-status" will thus be removed by apt.

R.

**Comment by C0rn3j** [comment]
>alter dependency to package "python2" and change "#!/usr/bin/python" to "#!/usr/bin/python2"

Python 2 is dead, things definitely shouldn't be hardcoded to use it.

If you want to alter the shebang line, it should be changed to `#!/usr/bin/env python` if anything.

**Comment by rlucassen2** [comment]
Ok, you're right, so option 2 (change the script to use python3 and change the dependency to package "python3") would be the right way. In Debian Bullseye (testing) the link /usr/bin/python does not exist anymore. I think a new "dist" directory "bullseye" should be added to the repository.

R.

**Comment by C0rn3j** [comment]
>change the script to use python3

The scripts are both Python 2.7 and 3.x compatible with the PR, your suggestion would kill the compatibility for 2.7.

```
In Debian Bullseye: the shebang line "#!/usr/bin/env python" throws:
/usr/bin/env: ‘python’: No such file or directory
```

Well, you're using beta releases, report a bug, system should definitely have `python` if Python is installed.

**Comment by rlucassen2** [comment]
I use the packages I find in "deb http://hwraid.le-vert.net/debian buster main" and this version of "megaclisas-status" script is definitivily not compatible with python3. There is no "bullseye" directory. And I'll file a bugreport for python.

R.

**Comment by glennsatchell** [comment]
any news on this request? I'm looking for an Ubuntu Focal version. Right now I just install the bionic package

**Comment by eLvErDe** [comment]
Hello,

It has been merged but redone because I wanted to also include black formatting

**Pull request closed without merging**
