### PR TITLE
Fixes for CacheCade, more than 16 LDs..

### PR DESCRIPTION
**Pull request by ElCoyote27**
Hi,
Here's a new set of bugfixes for:
1) cachecade systems
2) systems with more than 16 LD's per controller.
3) a few other fixes.

Tested fine on my systems.
Thanks,

Vincent

### CODE REVIEW

**Comment by txaj** [comment]
Your git history is pretty hard to read, could you please : 

- squash your commits when they are fixings typos of bugs in the code you just added ( https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit )
- make one PR per subject 

It makes the reviewing easier. 

Thanks

**Comment by ElCoyote27** [comment]
Hello,
I found a display bug when a drive has gone Bad. Could you please merge this revision?
Thank you,
Vincent

**Comment by ElCoyote27** [comment]
ping @eLvErDe

**Comment by eLvErDe** [comment]
Yup... way too busy these days, I'll let you know when available:/

On June 14, 2016 4:07:01 PM GMT+02:00, "Vincent S. Cojot" <notifications@github.com> wrote:
>ping @eLvErDe
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/eLvErDe/hwraid/pull/45#issuecomment-225891901

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ElCoyote27** [comment]
I'm going to re-submit a new and cleaner pull request..
Thanks,

**Pull request closed without merging**
